### PR TITLE
Fixes for CanJS 4

### LINKED ISSUE #20: can-react-component does not work as expected with CanJS 4
**Problem:** `can-react-component` does not work with `CanJS 4`

**Issues:**
- Bound properties are not working
- The component view is being rendered twice.

Here is a sample project that demonstrates the issues:
https://github.com/ivospinheiro/can-react-component-issue

### PR DESCRIPTION
**Pull request by christopherjbaker**
resolves #20, continues #21
* Update tests to test inserting the components on the page instead of using ReactTestUtils (thanks @ivospinheiro)
* on createComponent ref callback get the component viewModel from the element using can-symbol can.viewModel an assign the react props to viewModel (thanks @ivospinheiro)
* remove can-define from tests; use can-component builtins instead
* use can-reflect to modify viewmodel instance

### CODE REVIEW

**Comment by christopherjbaker** [comment]
@ivospinheiro I brought your code into a local branch so we can continue iterating on it. Your fix is what was needed, though I altered it to use [can-reflect.assign](https://canjs.com/doc/can-reflect.assign.html) instead of just `vm.assign`, and I took DefineMap out of the tests, since the can4 automatically turns the definitions into viewmodel instances (though the `SimpleMap` instances do not have `.assign` methods, hence the switch to can-reflect). Your `-issues` repo runs successfully with this code.

At present, this will mount the component without any data (causing the initial render), then immediately assign the props to the VM, causing a second render with the correct data. I am still looking into

**Comment by ivospinheiro** [comment]
> At present, this will mount the component without any data (causing the initial render), then immediately assign the props to the VM, causing a second render with the correct data. I am still looking into

@christopherjbaker I've noticed that but I had no idea how to fix that. What I understood was that the component was being rendered but with no initial data. Is there any way to set set the bound properties when creating the element on `render` function. Because the `ref` call will only be done after the component has been already rendered, I guess?

**Comment by ivospinheiro** [comment]
Hi @christopherjbaker and @justinbmeyer.
Can this pull request be accepted and `can-react-component` be released as it is and open a new issue to track the double rendering of the component?
Another question, is this package officially part of `CanJS 4/5`, because it is not listed on `canjs.com` website?

**Comment by christopherjbaker** [comment]
Released as [v2.0.0](https://github.com/canjs/can-react-component/releases/tag/v2.0.0), and opened #23 to address the issue of double rendering at mount.

**Comment by ivospinheiro** [comment]
@christopherjbaker many thanks.
This fix will unlock the upgrade from canJS@3 to canJS@5 that I'm working in.

**Comment by christopherjbaker** [comment]
Glad to be of service!

**Pull request merged**
